// AI guardrails — extends verifier.ts with EU AI Act Art. 9 risk management.
// Applied at orchestrator entry (input) and exit (output).

export interface GuardrailResult {
  allowed:    boolean;
  flags:      string[];       // human-readable issues found
  confidence: number;         // 0–100 estimated output quality
  requiresDisclaimer: boolean;
}

// Topics outside the scope of this HMO management system
const OUT_OF_SCOPE_INPUTS = [
  'immigration',    // immigration status determinations — ICO red line
  'asylum',
  'right to remain',
  'legal advice',
  'medical diagnosis',
  'prescribe',
  'criminal record check',
  'credit score',
  'evict',         // eviction is a legal process — AI cannot advise on this
];

// Protected characteristics under UK Equality Act 2010
// AI must not produce output that treats these as risk factors
const PROTECTED_CHARACTERISTICS = [
  'nationality', 'religion', 'race', 'ethnicity', 'sexual orientation',
  'disability', 'pregnancy', 'marriage', 'age',
];

// Patterns that suggest the AI is producing discriminatory content
const DISCRIMINATION_PATTERNS = [
  // Correlating protected characteristics with risk
  /because (?:of )?(?:their )?(nationality|religion|race|ethnicity|disability)/gi,
  /(?:nationality|religion|race) (?:suggests|indicates|is a factor)/gi,
];

/**
 * Validates the user's input before it reaches the LLM.
 * Prevents injection attempts and out-of-scope requests.
 */
export function checkInputGuardrails(task: string): GuardrailResult {
  const flags:  string[] = [];
  const lower   = task.toLowerCase();

  // 1. Scope check
  for (const topic of OUT_OF_SCOPE_INPUTS) {
    if (lower.includes(topic)) {
      flags.push(`Out of scope: "${topic}" — this system cannot advise on ${topic}`);
    }
  }

  // 2. Prompt injection detection
  const injectionPatterns = [
    /ignore (previous|all|your) instructions/i,
    /you are now/i,
    /disregard (your )?(system|guidelines)/i,
    /act as (?!a support worker|an assistant)/i,
    /jailbreak/i,
  ];
  for (const pat of injectionPatterns) {
    if (pat.test(task)) {
      flags.push('Possible prompt injection attempt detected');
      break;
    }
  }

  // 3. Length guard — very long inputs may be data exfiltration attempts
  if (task.length > 3000) {
    flags.push(`Input too long (${task.length} chars) — max 3000`);
  }

  return {
    allowed:            flags.filter((f) => f.startsWith('Out of scope') || f.includes('injection')).length === 0,
    flags,
    confidence:         100,
    requiresDisclaimer: false,
  };
}

/**
 * Validates the AI's output before it reaches the user.
 * Detects discriminatory content, hallucinations, and missing disclaimers.
 */
export function checkOutputGuardrails(
  response:    string,
  taskType:    string,
  riskDetected: boolean,
): GuardrailResult {
  const flags: string[] = [];
  let   confidence = 90; // base confidence

  // 1. Discrimination check
  for (const pattern of DISCRIMINATION_PATTERNS) {
    if (pattern.test(response)) {
      flags.push('Possible discriminatory reasoning detected — review before sharing');
      confidence -= 20;
      break;
    }
  }

  // 2. Check protected characteristics used as risk factors
  const lower = response.toLowerCase();
  for (const char of PROTECTED_CHARACTERISTICS) {
    if (lower.includes(char) && (lower.includes('risk') || lower.includes('concern') || lower.includes('flag'))) {
      flags.push(`Protected characteristic "${char}" appears near risk language — verify this is data-grounded`);
      confidence -= 10;
      break;
    }
  }

  // 3. Hallucination signals
  const hallucination = ['i cannot see', 'i don\'t have access', 'i have no information', 'according to my knowledge'];
  for (const phrase of hallucination) {
    if (lower.includes(phrase)) {
      flags.push('AI may be referencing general knowledge rather than tenant data');
      confidence -= 15;
      break;
    }
  }

  // 4. High-risk outputs need a disclaimer
  const requiresDisclaimer = taskType === 'brain' || riskDetected;

  // Confidence floor
  confidence = Math.max(confidence, 10);

  return {
    allowed:            true, // output guardrails warn but don't block (human reviews anyway)
    flags,
    confidence,
    requiresDisclaimer,
  };
}

/** Standard AI output disclaimer for high-risk task types */
export const AI_DISCLAIMER = `\n\n---\n*This output was generated by an AI system (EU AI Act classification: HIGH RISK). It is intended to assist — not replace — professional judgement. A qualified support worker or manager must review this before any action is taken.*`;
